### PR TITLE
Translation Portuguese (Portugal) pt_PT.po

### PR DESCRIPTION
**Pull request by rottenpants466**
Renamed pt.po to pt_PT.po.

In this way we have Portuguese (Portugal) and the existing Portuguese (Brazil) translations.

### CODE REVIEW

**Comment by rottenpants466** [comment]
Uh could some one help me out here. I dont know why the check failed :|

This is my first time contributing something so maybe i did something wrong?

**Comment by alainm23** [comment]
Thank you very much for helping to translate Planner. The error that Travis CLI gives is because the pt.po file does not exist. You should remove this line to fix it.

https://github.com/alainm23/planner/blob/master/po/LINGUAS#L136

However, the most recommended would be to add a new language.

**Comment by rottenpants466** [comment]
Uh could some one help me out here. I dont know why the check failed :|

This is my first time contributing something so maybe i did something wrong?

**Comment by rottenpants466** [comment]
Ok thanks. Should i close this pull request and make another one?

**Comment by alainm23** [comment]
Well, it depends on what you want to do. If you want to remove pt.po and replace it with pt_PT.po just remove that line above and add pt_PT. But the most recommended would be to add a new language, so for this you would have to close this PR and open a new one.

**Pull request closed without merging**
