### PR TITLE
Added Dutch translation

### PR DESCRIPTION
**Pull request by Vistaus**
:-)

### CODE REVIEW

**Comment by alainm23** [comment]
Thanks for the PR, but there are some mistakes to correct.

**Comment by Vistaus** [comment]
What mistakes?

**Comment by alainm23** [comment]
I'm sorry but I think you sent a PR to another project, this is Planner, not Optimizer

**Comment by Vistaus** [comment]
Oh crap, I uploaded the wrong translation. Sorry 'bout that!

**Pull request closed without merging**
