### PR TITLE
Added french translation

### PR DESCRIPTION
**Pull request by NathanBnm**

### CODE REVIEW

**Comment by alainm23** [comment]
Thank you very much for the translation, I hope to launch a next version this weekend

**Comment by NathanBnm** [comment]
You're welcome, it's a great app! :+1:

**Comment by mirzafawaz413-png** [comment]
Start karo

**Comment by mirzafawaz413-png** [comment]
Gta5 kalna vala ou

**Review by mirzafawaz413-png — COMMENTED** [review]
Bahai gta5 halado pleesa

**Pull request merged**
