### PR TITLE
Added Bulgarian translation

### PR DESCRIPTION
**Pull request by twlvnn**
This pull request contains the full Bulgarian translations on Planify. Please double-check if I added the language to the build process correctly to be sure.

### CODE REVIEW

**Comment by alainm23** [comment]
Translations were added correctly
image

**Comment by twlvnn** [comment]
The screenshot has the Hindi language but I think the merge also included the Hindi language update when I tried to sync because the LINGUAS file had a "hi" addition not just the "bg". Since you said I added it correctly to the build process it should be good though, thank you!

**Comment by alainm23** [comment]
I'm sorry, I do now.

image

**Comment by twlvnn** [comment]
It looks perfect, thank you so much for verifying!

**Pull request merged**
