### PR TITLE
Translation PT_BR

### PR DESCRIPTION
**Pull request by gleissonjoaquim3**
Update po file , with translation pt_BR.

### CODE REVIEW

**Comment by gleissonjoaquim3** [comment]
@alainm23 i don't know what is this conflicts error...

**Comment by alainm23** [comment]
I understand, I would recommend you to do a folk again and send a PR again.

**Comment by gleissonjoaquim3** [comment]
i'll try... 
I will have to make a new PR ?

**Comment by alainm23** [comment]
Yes, it would be best 😅️.

**Pull request closed without merging**
