### PR TITLE
Changed item spacing in pane and bold only for selected item

### PR DESCRIPTION
**Pull request by ni-ka**
planner-item-spacing

### CODE REVIEW

**Comment by alainm23** [comment]
Thanks. Why did you decide to change the space between each item? I'm not sure to apply bold to a selected item because folders already use a bold label.

**Comment by ni-ka** [comment]
Sorry my description should have been clearer. I found the current style (everything bold) a bit straining on the eye, so I removed the bold on all items and replaced with selected only. The spacing look better to me, also took inspiration from the todoist UI.

Check a comparison (from left to right: planner master, planner this branch, todoist):
sidebar-styles

**Comment by alainm23** [comment]
Thank you very much.

**Comment by 4jNsY6fCVqZv** [comment]
> I found the current style (everything bold) a bit straining on the eye

Hello, I don't understand the issue yet. I use the native version 2.3.5 for from the elementary AppCenter. Also with the native button layout. In both the Dark Theme and the Light Theme, only the views and folder names are bold. Everything else is not.

**Pull request merged**
